name: Calculator CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get Calculator Files
        uses: actions/checkout@v4

      - name: Test Calculator
        run: |
          echo "Testing Calculator..."
          echo "This test will fail intentionally."
          exit 1
